name: Fetch Grafana Versions

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at midnight on every 10th day of the month

jobs:
  fetch_tomcat_versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Latest Grafana Version
        run: |
         latest_version=$(curl -s https://api.github.com/repos/grafana/grafana/releases/latest | grep -oP '"tag_name": "\K[0-9\.]+')
         # Output the latest version
         echo "Latest Grafana version: $latest_version" 
