name: Fetch Prometheus Grafana Versions

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *' # Runs at 00:00, on day 1 of the month, only in January, April, July, and October.

jobs:
  fetch_promgraf_versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Latest Prometheus Version
        run: |
          PROM_V_LATEST_VERSION=$(curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
          echo ${PROM_V_LATEST_VERSION}
          PROM_LATEST_VERSION=$(echo "${PROM_V_LATEST_VERSION}" | cut -c 2-)
          echo ${PROM_LATEST_VERSION}
 
          sed -i " 5 c LATEST_VERSION=${PROM_LATEST_VERSION} " prometheus.sh 
          

      - name: Fetch Latest Grafana Version
        run: |
           GRAF_V_LATEST_VERSION=$(curl -s https://api.github.com/repos/grafana/grafana/releases/latest | jq -r '.tag_name')
           echo ${GRAF_V_LATEST_VERSION}
           GRAF_LATEST_VERSION=$(echo "${GRAF_V_LATEST_VERSION}" | cut -c 2-)
           echo ${GRAF_LATEST_VERSION}

           sed -i " 4 c LATEST_VERSION=${GRAF_LATEST_VERSION} " grafana.sh

      - name: Fetch Latest Grafana Version
        run: |
           latest_version=$(curl -s https://api.github.com/repos/prometheus/node_exporter/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')  
           echo $latest_version
